### ISSUE TITLE
TypeScript error when deconstructing values from provider hook

### ISSUE THREAD

**Issue by ArekBartnik** [kyleshevlin/react-generate-context#4]
TypeScript is showing error when I try to deconstruct values from the provider hook.

```
const [count, { inc, dec }] = useCounter()
// Type '(number | { inc: () => void; dec: () => void; reset: () => void; })[] | undefined' is not an array type.ts(2461)
```

I think it's because of this line
https://github.com/kyleshevlin/react-generate-context/blob/3fec1be695d0305a8a362afaece3ee74a2a929f0/src/index.tsx#L15

Is `undefined` necessary here?

**Comment by kyleshevlin** [comment]
Please add the rest of the code you're using to generate the `useCounter` in this example to this issue. It may help explain your issue.

The `undefined` is necessary because you do not need to have a `defaultContextValue`. It is optional. Without a default `value`, it is possible for a Context to return `undefined` when used outside of a Provider.

The type you have there has mistakes. It is returning an Array type, not a Tuple type. It should be a Tuple of `[number, handlers]` (where `handlers` is a short hand for the object of handlers you are returning).

**Comment by ArekBartnik** [comment]
I've made a codesanbox https://codesandbox.io/s/generate-context-hsy9b
What could I do to remove error in line 34?

**Comment by kyleshevlin** [comment]
Thanks for providing an example. It does seem like there's an improvement that can be made.

The way around it for now is honoring the type. It _is_ possible to use the hook outside of its corresponding Provider, and thus the type checker is correctly telling you it could be `undefined`. You can get around it with:

```typescript
const counterCtx = useCounterContext()

if (!counterCtx) return null

const [count, { inc, dec, reset }] = counterCtx
```

This works because `counterCtx` is narrowed to type `Context` with the `if` check on the line above.

That said, I think I can improve the types such that it does not require this check if either a `defaultContext` has been provided, or `requireProvider` has been set to `true`. If a `defaultContext` has been provided, then the Context returned will never be `undefined`. Also, if `requireProvider` is `true` (which is the default), then we are guaranteeing that it will not be used outside of its Provider.

I will look into these soon. Might be a few days, I don't code a lot on the weekends.
